// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddQuickLink(arg1:string,arg2:string):Promise<Array<main.QuickLink>>;

export function CheckStatus(arg1:string):Promise<main.ProjectStatus>;

export function CheckoutCommit(arg1:string,arg2:string):Promise<string>;

export function CreateBranch(arg1:string,arg2:string):Promise<string>;

export function GetBranchColor(arg1:string,arg2:string):Promise<string>;

export function GetBranches(arg1:string):Promise<Array<string>>;

export function GetCommitHistory(arg1:string,arg2:string):Promise<Array<main.Commit>>;

export function GetCommitTree(arg1:string,arg2:string):Promise<Array<string>>;

export function GetConfig():Promise<main.Config>;

export function GetContributionStats(arg1:string):Promise<main.ContributionStats>;

export function GetCurrentBranch(arg1:string):Promise<string>;

export function GetFileAtCommit(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetFileDiffAtCommit(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetGitHubURL(arg1:string):Promise<string>;

export function GetModifiedFiles(arg1:string):Promise<Array<main.FileStatus>>;

export function GetPRURL(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetQuickLinks():Promise<Array<main.QuickLink>>;

export function GetRecentProjects():Promise<Array<main.Project>>;

export function GetSubfolders(arg1:string):Promise<Array<string>>;

export function OpenInVSCode(arg1:string):Promise<string>;

export function OpenTerminal(arg1:string):Promise<string>;

export function OpenURL(arg1:string):Promise<string>;

export function PullRepo(arg1:string):Promise<main.SyncResult>;

export function RemoveQuickLink(arg1:string):Promise<Array<main.QuickLink>>;

export function SaveRecentProject(arg1:string):Promise<void>;

export function ScanProjects(arg1:string):Promise<Array<main.Project>>;

export function SelectDirectory():Promise<string>;

export function SetBranchColor(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetRootDir(arg1:string):Promise<void>;

export function SuperSync(arg1:string,arg2:Array<string>,arg3:string):Promise<main.SyncResult>;

export function SwitchBranch(arg1:string,arg2:string):Promise<string>;

export function UseQuickLink(arg1:string):Promise<Array<main.QuickLink>>;
