// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddQuickLink(arg1, arg2) {
  return window['go']['main']['App']['AddQuickLink'](arg1, arg2);
}

export function CheckStatus(arg1) {
  return window['go']['main']['App']['CheckStatus'](arg1);
}

export function CheckoutCommit(arg1, arg2) {
  return window['go']['main']['App']['CheckoutCommit'](arg1, arg2);
}

export function GetBranches(arg1) {
  return window['go']['main']['App']['GetBranches'](arg1);
}

export function GetCommitHistory(arg1, arg2) {
  return window['go']['main']['App']['GetCommitHistory'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetContributionStats(arg1) {
  return window['go']['main']['App']['GetContributionStats'](arg1);
}

export function GetCurrentBranch(arg1) {
  return window['go']['main']['App']['GetCurrentBranch'](arg1);
}

export function GetGitHubURL(arg1) {
  return window['go']['main']['App']['GetGitHubURL'](arg1);
}

export function GetModifiedFiles(arg1) {
  return window['go']['main']['App']['GetModifiedFiles'](arg1);
}

export function GetQuickLinks() {
  return window['go']['main']['App']['GetQuickLinks']();
}

export function GetRecentProjects() {
  return window['go']['main']['App']['GetRecentProjects']();
}

export function GetSubfolders(arg1) {
  return window['go']['main']['App']['GetSubfolders'](arg1);
}

export function OpenInVSCode(arg1) {
  return window['go']['main']['App']['OpenInVSCode'](arg1);
}

export function OpenTerminal(arg1) {
  return window['go']['main']['App']['OpenTerminal'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RemoveQuickLink(arg1) {
  return window['go']['main']['App']['RemoveQuickLink'](arg1);
}

export function SaveRecentProject(arg1) {
  return window['go']['main']['App']['SaveRecentProject'](arg1);
}

export function ScanProjects(arg1) {
  return window['go']['main']['App']['ScanProjects'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetRootDir(arg1) {
  return window['go']['main']['App']['SetRootDir'](arg1);
}

export function SuperSync(arg1, arg2, arg3) {
  return window['go']['main']['App']['SuperSync'](arg1, arg2, arg3);
}

export function SwitchBranch(arg1, arg2) {
  return window['go']['main']['App']['SwitchBranch'](arg1, arg2);
}

export function UseQuickLink(arg1) {
  return window['go']['main']['App']['UseQuickLink'](arg1);
}
